services:
  - type: worker
    name: raspisanie-bot
    runtime: docker
    dockerfilePath: ./bot/Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_IDS
        sync: false
